### ISSUE TITLE
This is indeed very sus

### ISSUE THREAD

**Issue by Puh00** [Bobbelty/TrainingApp#1]
https://github.com/Bobbelty/TrainingApp/blob/0c24f038bc5a993965c9984736cd67f14d984652/app/src/main/java/model/Plan.java#L17

[https://dzone.com/articles/how-do-i-compare-strings-in-java](https://dzone.com/articles/how-do-i-compare-strings-in-java)

**Comment by Valle20** [comment]
Resolved 98cddbb03c0a7a31d52a010f59b8ce908ab78333
